
-- create
CREATE TABLE ESTOQUE (
  Id INTEGER PRIMARY KEY,
  PRODUTO varchar(50) NOT NULL,
  CATEGORIA TEXT NOT NULL,
  QUANTIDADE int
);

-- insert
INSERT INTO ESTOQUE VALUES (0001, 'CHICLETE', 'ALIMENTOS', 50);
INSERT INTO ESTOQUE VALUES (0002, 'REMO', 'PESCA', 3);
INSERT INTO ESTOQUE VALUES (0003, 'DICIONÁRIO', 'LIVROS', 20);

SELECT * FROM ESTOQUE;


SELECT * FROM ESTOQUE where CATEGORIA = 'PESCA' AND QUANTIDADE = 50;
