-- create
CREATE TABLE ALUNOS (
  Id INTEGER PRIMARY KEY,
  NOME varchar(50),
  NOTA_FINAL int
);

-- insert
INSERT INTO ALUNOS VALUES (0001,'JOÃOZINHO', 10);
INSERT INTO ALUNOS VALUES (0002,'MARIAZINHA', 8);
INSERT INTO ALUNOS VALUES (0003,'WALDISNEY', 3);

SELECT * FROM ALUNOS;


SELECT AVG(NOTA_FINAL) FROM ALUNOS;

SELECT MAX(NOTA_FINAL) FROM ALUNOS;
