-- create
CREATE TABLE PEDIDOS (
  Id INTEGER PRIMARY KEY,
  REGIÃO varchar(50),
  NUMERO_DE_VENDAS int
);

-- insert
INSERT INTO PEDIDOS VALUES (0001,'SUL', 1000);
INSERT INTO PEDIDOS VALUES (0002,'NORTE', 800);
INSERT INTO PEDIDOS VALUES (0003,'NORDESTE', 300);

SELECT REGIÃO,SUM(NUMERO_DE_VENDAS) from PEDIDOS group by REGIÃO having SUM(NUMERO_DE_VENDAS) >=500;
